### ISSUE TITLE
[FEATURE] README 내용 추가

### ISSUE THREAD

**Issue by mjjeon2645** [wanted-pre-onboarding-team-9/pre-onboarding-10th-2-9#17]
### 🤸 Describe the required feature
- 기본 README 템플릿을 바탕으로 내용 보완

### 🏊 Todo

- [x] 지난 프로젝트 README 템플릿을 활용하여 프로젝트 정보 보완
- [x] 과제 요구사항에서 설명을 요하는 내용 추가
  - [x] 캐싱 구현 방법
  - [x] 입력마다 API 호출하지 않도록 API 호출 횟수를 줄이는 전략 수립 및 실행
  - [x] 키보드만으로 추천 검색어들로 이동하는 방법
