### ISSUE TITLE
[FEATURE] Best Practice 리팩터링

### ISSUE THREAD

**Issue by mjjeon2645** [wanted-pre-onboarding-team-9/pre-onboarding-10th-2-9#9]
### 🤸 Describe the required feature
- 개인 과제에 대한 리뷰 및 회의를 통해 Best Practice 선정
- 선정된 Best Practice 관련 추가 보완사항 의논하여 반영

### 🏊 Todo

- [ ] localStorage로 구현된 Cache 기능을 Context API 활용안으로 전환
- [ ] 추천 검색어 결과값이 8개를 초과할 경우 상위 8개까지 저장 및 노출
- [ ] 추천 검색어를 키보드로 선택한 상태에서 enter키 누를 경우 input 텍스트가 선택한 검색어로 변경되도록 함
- [ ] 추천 검색어를 마우스로 클릭할 경우 input 텍스트가 선택한 검색어로 변경되도록 함
- [ ] 검색창 바깥 영역 클릭 시 드롭다운 비활성화
- [ ] 컴포넌트 분리
- [ ] proxy로 CORS 우회
- [ ] README.md 수정
